#### 데이터 설명 : 비행탑승 경험 만족도
#### x_train: https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/x_train.csv
#### x_test: https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/x_test.csv
출처 (참고, 데이터 수정)

In [ ]:
import pandas as pd
train = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/x_train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/x_test.csv')

In [ ]:
train.head()

,ID,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,id
0,0,Female,Loyal Customer,54,Personal Travel,Eco,1068,3,4,3,...,5,5,3,5,3,5,3,47,22.0,NaN
1,2,Male,Loyal Customer,20,Personal Travel,Eco,1546,4,4,4,...,4,3,3,4,4,4,4,5,2.0,NaN
2,3,Male,Loyal Customer,59,Business travel,Business,2962,0,4,0,...,1,1,1,1,5,1,4,54,46.0,NaN
3,4,Male,Loyal Customer,35,Business travel,Eco Plus,106,5,4,4,...,5,2,1,5,4,4,5,130,121.0,NaN
4,5,Female,Loyal Customer,9,Business travel,Business,2917,3,3,3,...,4,4,4,5,4,3,4,0,0.0,NaN

In [ ]:
test.head()

,ID,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,id
0,1,Male,Loyal Customer,28,Business travel,Business,3414,2,2,2,...,2,4,5,4,4,4,2,0,0.0,40819.0
1,16,Female,disloyal Customer,34,Business travel,Eco,2556,1,1,1,...,2,5,1,5,1,3,2,15,0.0,33335.0
2,17,Female,Loyal Customer,23,Personal Travel,Eco,363,2,5,2,...,5,3,2,4,5,4,5,0,0.0,20749.0
3,25,Male,Loyal Customer,55,Business travel,Business,2079,1,1,1,...,1,1,1,1,4,1,3,0,0.0,92194.0
4,27,Female,Loyal Customer,44,Business travel,Eco,192,2,4,5,...,1,1,2,1,5,1,1,23,13.0,13904.0

## 1. MinMaxScaler

### Question. train 데이터의 Age 컬럼을 MinMax 스케일링하여 얻은 값을 age_mm_scaling 컬럼에 추가한 후, train셋과 같은 기준으로 test 데이터의 Age를 스케일링하고 그 결과를 age_mm_scaling 컬럼에 추가하라.

####step1. 'MinMaxScaler'를 사용하기 위한 라이브러리를 import하기

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
train = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/x_train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/x_test.csv')

#### step2. MinMaxScaler 객체 생성

In [ ]:
mm = MinMaxScaler()

#### step3. train 데이터의 Age를 2차원 형태로 변환 후 이를 a1이라는 데이터로 저장

In [ ]:
train_age = train[['Age']]
train_age.head()

   Age
0   54
1   20
2   59
3   35
4    9

#### step4. MinMaxScaler 객체를 사용하여 데이터를 학습

In [ ]:
mm.fit(train_age)

MinMaxScaler()

#### step5. 학습된 MinMaxScaler 객체를 사용하여 'Age'열의 데이터를 변환하고, 'age_scaling'컬럼에 추가

In [ ]:
train['age_mm_scaling'] = mm.transform(train_age)
train.head()

,ID,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,id,age_mm_scaling
0,0,Female,Loyal Customer,54,Personal Travel,Eco,1068,3,4,3,...,5,3,5,3,5,3,47,22.0,NaN,0.602564
1,2,Male,Loyal Customer,20,Personal Travel,Eco,1546,4,4,4,...,3,3,4,4,4,4,5,2.0,NaN,0.166667
2,3,Male,Loyal Customer,59,Business travel,Business,2962,0,4,0,...,1,1,1,5,1,4,54,46.0,NaN,0.666667
3,4,Male,Loyal Customer,35,Business travel,Eco Plus,106,5,4,4,...,2,1,5,4,4,5,130,121.0,NaN,0.358974
4,5,Female,Loyal Customer,9,Business travel,Business,2917,3,3,3,...,4,4,5,4,3,4,0,0.0,NaN,0.025641

#### step6. test 데이터에서도 'Age'컬럼을 추출하여 2차원 배열 형태로 변환하고, 학습된 MinMaxScaler 객체를 사용하여 test 데이터의 'Age'열을 변환 후 이를 'age_mm_scaling'컬럼에 추가

In [ ]:
train_age = test[['Age']]
test['age_mm_scaling'] = mm.transform(train_age)
test.head()

,ID,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,id,age_mm_scaling
0,1,Male,Loyal Customer,28,Business travel,Business,3414,2,2,2,...,4,5,4,4,4,2,0,0.0,40819.0,0.269231
1,16,Female,disloyal Customer,34,Business travel,Eco,2556,1,1,1,...,5,1,5,1,3,2,15,0.0,33335.0,0.346154
2,17,Female,Loyal Customer,23,Personal Travel,Eco,363,2,5,2,...,3,2,4,5,4,5,0,0.0,20749.0,0.205128
3,25,Male,Loyal Customer,55,Business travel,Business,2079,1,1,1,...,1,1,1,4,1,3,0,0.0,92194.0,0.615385
4,27,Female,Loyal Customer,44,Business travel,Eco,192,2,4,5,...,1,2,1,5,1,1,23,13.0,13904.0,0.474359

## 2. StandardScaler

### Question. train 데이터의 Age 컬럼을 sklearn 모듈을 활용하여 정규화 스케일링한 결과를 age_s_scaling 컬럼에 추가한 후, train셋과 같은 기준으로 test 데이터의 Age를 스케일링하여 age_s_scaling 컬럼에 추가하라.

#### step1. 'StandScaler'를 사용하기 위한 라이브러리를 import하기

In [ ]:
from sklearn.preprocessing import StandardScaler

#### step2. StandardScaler 객체 생성

In [ ]:
std = StandardScaler()

#### step3. train 데이터의 Age를 2차원 형태로 변환 후 이를 a1라는 데이터로 저장

In [ ]:
a1 = train[['Age']]
a1.head()

   Age
0   54
1   20
2   59
3   35
4    9

#### step4. StandScaler 객체를 사용하여 데이터를 학습

In [ ]:
std.fit(a1)

StandardScaler()

#### step5. 학습된  StandardScaler 객체를 사용하여 'Age'열의 데이터를 변환하고, 'age_s_scaling'컬럼에 추가

In [ ]:
train['age_mm_scaling'] = std.transform(train_age)
train.head()

,ID,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,id,age_mm_scaling
0,0,Female,Loyal Customer,54,Personal Travel,Eco,1068,3,4,3,...,5,3,5,3,5,3,47,22.0,NaN,0.969366
1,2,Male,Loyal Customer,20,Personal Travel,Eco,1546,4,4,4,...,3,3,4,4,4,4,5,2.0,NaN,-1.281932
2,3,Male,Loyal Customer,59,Business travel,Business,2962,0,4,0,...,1,1,1,5,1,4,54,46.0,NaN,1.300439
3,4,Male,Loyal Customer,35,Business travel,Eco Plus,106,5,4,4,...,2,1,5,4,4,5,130,121.0,NaN,-0.288712
4,5,Female,Loyal Customer,9,Business travel,Business,2917,3,3,3,...,4,4,5,4,3,4,0,0.0,NaN,-2.010293

#### step6. test 데이터에서도 'Age'컬럼을 추출하여 2차원 배열 형태로 변환하고, 학습된 StandardScaler 객체를 사용하여 test데이터의 'Age'열을 변환 후 'age_s_scaling'컬럼에 추가

In [ ]:
train_age = test[['Age']]
test['age_std_scaling'] = std.transform(train_age)
test.head()

,ID,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,id,age_mm_scaling,age_std_scaling
0,1,Male,Loyal Customer,28,Business travel,Business,3414,2,2,2,...,5,4,4,4,2,0,0.0,40819.0,0.269231,-0.752215
1,16,Female,disloyal Customer,34,Business travel,Eco,2556,1,1,1,...,1,5,1,3,2,15,0.0,33335.0,0.346154,-0.354927
2,17,Female,Loyal Customer,23,Personal Travel,Eco,363,2,5,2,...,2,4,5,4,5,0,0.0,20749.0,0.205128,-1.083288
3,25,Male,Loyal Customer,55,Business travel,Business,2079,1,1,1,...,1,1,4,1,3,0,0.0,92194.0,0.615385,1.035580
4,27,Female,Loyal Customer,44,Business travel,Eco,192,2,4,5,...,2,1,5,1,1,23,13.0,13904.0,0.474359,0.307219

#### train 데이터에 추가된 age_mm_scaling 칼럼과 age_s_scaling 칼럼 확인하기

In [ ]:
train.head()

,ID,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,id,age_mm_scaling
0,0,Female,Loyal Customer,54,Personal Travel,Eco,1068,3,4,3,...,5,3,5,3,5,3,47,22.0,NaN,0.969366
1,2,Male,Loyal Customer,20,Personal Travel,Eco,1546,4,4,4,...,3,3,4,4,4,4,5,2.0,NaN,-1.281932
2,3,Male,Loyal Customer,59,Business travel,Business,2962,0,4,0,...,1,1,1,5,1,4,54,46.0,NaN,1.300439
3,4,Male,Loyal Customer,35,Business travel,Eco Plus,106,5,4,4,...,2,1,5,4,4,5,130,121.0,NaN,-0.288712
4,5,Female,Loyal Customer,9,Business travel,Business,2917,3,3,3,...,4,4,5,4,3,4,0,0.0,NaN,-2.010293

#### test 데이터에 추가된 age_mm_scaling 칼럼과 age_s_scaling 칼럼 확인하기

In [ ]:
test.head()

,ID,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,id,age_mm_scaling,age_std_scaling
0,1,Male,Loyal Customer,28,Business travel,Business,3414,2,2,2,...,5,4,4,4,2,0,0.0,40819.0,0.269231,-0.752215
1,16,Female,disloyal Customer,34,Business travel,Eco,2556,1,1,1,...,1,5,1,3,2,15,0.0,33335.0,0.346154,-0.354927
2,17,Female,Loyal Customer,23,Personal Travel,Eco,363,2,5,2,...,2,4,5,4,5,0,0.0,20749.0,0.205128,-1.083288
3,25,Male,Loyal Customer,55,Business travel,Business,2079,1,1,1,...,1,1,4,1,3,0,0.0,92194.0,0.615385,1.035580
4,27,Female,Loyal Customer,44,Business travel,Eco,192,2,4,5,...,2,1,5,1,1,23,13.0,13904.0,0.474359,0.307219